### ISSUE TITLE
Be able to explicitly delete a workspace

### ISSUE THREAD

**Issue by vechema** [theotherjimmy/lanta#4]
When a workspace is empty, it'd be nice to be able to delete it. Current workaround - move all windows from the last workspace into empty workspace, rename formally empty workspace appropriately, last workspace is deleted.

**Comment by theotherjimmy** [comment]
With the most recent commit, you can now do this by binding a key to the `CloseDesktop` action. Note that you can not close a desktop if:
  * Closing the desktop would leave you with fewer desktops than you have screens
  * The desktop contains windows.

I think these are reasonable limitations.
